local options = require("user.options")
local plugins = require("user.plugins")
local colors = require("user.colors")
local telescope = require("user.telescope")
local keymap = require("user.keymap")
local treesitter = require("user.treesitter")
local completion = require("user.completion")
local lsp = require("user.lsp")
local gitsigns = require("user.gitsigns")
local tree = require("user.tree")
local comment = require("user.comment")
local bufferline = require("user.bufferline")
local autopairs = require("user.autopairs")
local lualine = require("user.lualine")
local luasnip = require("user.luasnip")
local colorizer = require("user.colorizer")

options.setup()
plugins.setup()
colors.setup()
telescope.setup()
keymap.setup()
treesitter.setup()
completion.setup()
lsp.setup()
gitsigns.setup()
comment.setup()
bufferline.setup()
autopairs.setup()
lualine.setup()
luasnip.setup()
colorizer.setup()
